FROM golang:1.13 AS build
WORKDIR /src/fe
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go install -a -tags netgo -ldflags=-w

FROM gcr.io/distroless/base
ARG VER=0
ENV VER $VER
ENV DEBUG 0
COPY --from=build /go/bin/fe /bin/fe
EXPOSE 8080
ENTRYPOINT [ "/bin/fe" ]
