kind: Secret
apiVersion: v1
metadata:
  name: api-keys
type: Opaque
data:
  google-key: "QUl6YVN5RGdSWTNEejRCenFwekxXRG1JU1JhSm80ejlDLXBvNXpnCg=="
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        version: v1
    spec:
      serviceAccountName: myapp-sa
      containers:
      - name: myapp-container
        image: gcr.io/your_project/fe_min:1
        #image: gcr.io/sd-test-246101/fe_min:debug1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: settings
              key: GOOGLE_CLOUD_PROJECT
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: settings
              key: BUCKET_NAME
        - name: GKE_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: settings
              key: GKE_CLUSTER_NAME
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: google-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-v2
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: myapp
        version: v2
    spec:
      containers:
      - name: myapp-container
        image: gcr.io/your_project/fe_min:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: settings
              key: GOOGLE_CLOUD_PROJECT
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: settings
              key: BUCKET_NAME
        - name: GKE_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: settings
              key: GKE_CLUSTER_NAME
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: google-key
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: be-sa
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: be-v1
  labels:
    type: be
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: be
        version: v1
    spec:
      serviceAccountName: be-sa
      containers:
      - name: be-container
        image: gcr.io/your_project/be_min:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: settings
              key: GOOGLE_CLOUD_PROJECT
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: settings
              key: BUCKET_NAME
        - name: GKE_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: settings
              key: GKE_CLUSTER_NAME
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: be-v2
  labels:
    type: be
    version: v2
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: be
        version: v2
    spec:
      serviceAccountName: be-sa
      containers:
      - name: be-container
        image: gcr.io/your_project/be_min:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            configMapKeyRef:
              name: settings
              key: GOOGLE_CLOUD_PROJECT
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: settings
              key: BUCKET_NAME
        - name: GKE_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: settings
              key: GKE_CLUSTER_NAME
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
